# Generated by Django 3.1.14 on 2024-02-26 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('subdomain', models.SlugField(max_length=100, unique=True)),
                ('domain', models.CharField(blank=True, max_length=128, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=128)),
                ('nav', models.CharField(blank=True, default='[Home](/) [Blog](/blog/)', max_length=1000)),
                ('content', models.TextField(blank=True, default='Hello World!')),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('meta_image', models.CharField(blank=True, max_length=200)),
                ('lang', models.CharField(blank=True, default='en', max_length=10)),
                ('meta_tag', models.CharField(blank=True, max_length=500)),
                ('blog_path', models.CharField(default='blog', max_length=200)),
                ('header_directive', models.TextField(blank=True)),
                ('footer_directive', models.TextField(blank=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('ignored_date', models.DateTimeField(blank=True, null=True)),
                ('to_review', models.BooleanField(default=False)),
                ('reviewer_note', models.TextField(blank=True)),
                ('upgraded', models.BooleanField(default=False)),
                ('upgraded_date', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('custom_styles', models.TextField(blank=True)),
                ('overwrite_styles', models.BooleanField(choices=[(True, 'Overwrite default styles'), (False, 'Extend default styles')], default=False, verbose_name='')),
                ('favicon', models.CharField(default='🐼', max_length=10)),
                ('dashboard_styles', models.TextField(blank=True)),
                ('dashboard_footer', models.TextField(blank=True)),
                ('date_format', models.CharField(blank=True, max_length=32)),
                ('analytics_active', models.BooleanField(default=True)),
                ('fathom_site_id', models.CharField(blank=True, max_length=8)),
                ('public_analytics', models.BooleanField(default=False)),
                ('post_template', models.TextField(blank=True)),
                ('robots_txt', models.TextField(blank=True)),
                ('rss_alias', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersistentStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_executed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=200)),
                ('published_date', models.DateTimeField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('all_tags', models.TextField(default='[]')),
                ('publish', models.BooleanField(default=True)),
                ('make_discoverable', models.BooleanField(default=True)),
                ('is_page', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('canonical_url', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('meta_image', models.CharField(blank=True, max_length=200)),
                ('lang', models.CharField(blank=True, max_length=10)),
                ('class_name', models.CharField(blank=True, max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Stylesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('identifier', models.SlugField(max_length=100, unique=True)),
                ('css', models.TextField(blank=True)),
                ('external', models.BooleanField(default=False)),
                ('image', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('hash_id', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.post')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
            ],
        ),
        migrations.CreateModel(
            name='RssSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('hash_id', models.CharField(max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('hash_id', models.CharField(max_length=200)),
                ('referrer', models.URLField(blank=True, default=None, null=True)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('device', models.CharField(blank=True, max_length=200)),
                ('browser', models.CharField(blank=True, max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.post')),
            ],
        ),
    ]
