# Generated by Django 3.0.6 on 2020-05-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='slug',
            new_name='subdomain',
        ),
    ]
