# Generated by Django 3.0.6 on 2020-05-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
