# Generated by Django 3.1.14 on 2024-02-27 07:22

from django.db import migrations, models
import django.db.models.deletion

def update_user_settings_from_blog(apps, schema_editor):
    UserSettings = apps.get_model('blogs', 'UserSettings')
    Blog = apps.get_model('blogs', 'Blog')
    
    for user_setting in UserSettings.objects.all():
        user = user_setting.user
        first_blog = Blog.objects.filter(user=user).first()
        if first_blog:
            user_setting.dashboard_styles = first_blog.dashboard_styles
            user_setting.dashboard_footer = first_blog.dashboard_footer
            user_setting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20240226_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='dashboard_footer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='dashboard_styles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.blog'),
        ),
        migrations.RunPython(update_user_settings_from_blog),
    ]
