# Generated by Django 3.1.14 on 2024-02-28 09:09

from django.db import migrations, models
def update_user_settings_from_blog(apps, schema_editor):
    Blog = apps.get_model('blogs', 'Blog')
    
    for blog in Blog.objects.filter(blocked=True):
        blog.user.is_active = False
        blog.user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20240227_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(update_user_settings_from_blog),
    ]
