# Generated by Django 3.0.6 on 2020-05-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_delete_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='domain',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
