# Generated by Django 3.0.6 on 2020-05-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='domain_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subdomain_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
