# Generated by Django 3.1.14 on 2024-02-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20240228_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='upgraded_date',
        ),
    ]
