# Generated by Django 3.1.14 on 2024-02-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_blog_upgraded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='order_id',
        ),
    ]
