# Generated by Django 3.0.6 on 2020-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_blog_domain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='domain',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
