# Generated by Django 3.1.14 on 2024-02-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_blog_upgraded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='dashboard_footer',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='dashboard_styles',
        ),
    ]
