# Generated by Django 3.0.6 on 2020-05-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subdomain_id',
        ),
    ]
