# Generated by Django 3.1.14 on 2024-02-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_remove_blog_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentstore',
            name='review_ignore_terms',
            field=models.TextField(blank=True),
        ),
    ]
