# Generated by Django 3.0.6 on 2020-06-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20200531_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='hashtags',
            field=models.TextField(blank=True),
        ),
    ]
