# Generated by Django 3.1.14 on 2024-03-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_persistentstore_review_ignore_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentstore',
            name='review_highlight_terms',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='persistentstore',
            name='review_ignore_terms',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
