# Generated by Django 3.1.14 on 2024-04-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20240307_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='deprioritise',
            field=models.BooleanField(default=False),
        ),
    ]
