# Generated by Django 3.0.6 on 2020-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20200601_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_in_feed',
            field=models.BooleanField(default=True),
        ),
    ]
