# Generated by Django 3.1.14 on 2024-04-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_blog_deprioritise'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
