# Generated by Django 3.0.7 on 2020-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_post_show_in_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
