# Generated by Django 3.0.7 on 2020-06-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_pageview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp']},
        ),
    ]
