# Generated by Django 3.0.7 on 2020-08-24 14:10

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blogs', '0014_post_canonical_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
