# Generated by Django 3.1.14 on 2024-05-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_blog_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='favicon',
            field=models.CharField(blank=True, default='🐼', max_length=100),
        ),
    ]
