# Generated by Django 3.0.7 on 2020-08-31 08:30

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blogs', '0015_auto_20200824_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reviewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
