# Generated by Django 3.1.14 on 2024-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20240530_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='nav',
            field=models.TextField(blank=True, default='[Home](/) [Blog](/blog/)'),
        ),
    ]
