# Generated by Django 3.0.7 on 2020-06-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20200609_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageview',
            old_name='referrer',
            new_name='referer',
        ),
    ]
