# Generated by Django 3.1.14 on 2024-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20240605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
