# Generated by Django 3.0.7 on 2020-08-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20200831_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
