# Generated by Django 3.1.14 on 2024-06-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_post_first_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dodginess_score',
            field=models.FloatField(default=0),
        ),
    ]
