# Generated by Django 3.1.14 on 2024-06-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_blog_dodginess_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deprioritise',
            field=models.BooleanField(default=False),
        ),
    ]
