# Generated by Django 3.0.7 on 2020-10-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_blog_upgraded'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='custom_styles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='remove_branding',
            field=models.BooleanField(default=False),
        ),
    ]
