# Generated by Django 3.0.7 on 2020-10-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_blog_upgraded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blogs.Blog')),
                ('background_color', models.CharField(blank=True, max_length=5)),
                ('font_color', models.CharField(blank=True, max_length=5)),
                ('heading_color', models.CharField(blank=True, max_length=5)),
                ('link_color', models.CharField(blank=True, max_length=5)),
                ('font_family', models.CharField(blank=True, max_length=200)),
                ('custom_css', models.TextField(blank=True)),
            ],
        ),
    ]
