# Generated by Django 3.1.14 on 2024-08-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deprioritise',
        ),
        migrations.AddField(
            model_name='post',
            name='shadow_votes',
            field=models.IntegerField(default=0),
        ),
    ]
