# Generated by Django 3.0.7 on 2020-10-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='background_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='style',
            name='font_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='style',
            name='heading_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='style',
            name='link_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
