# Generated by Django 3.0.7 on 2020-10-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_auto_20201022_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='allow_dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
