# Generated by Django 3.0.7 on 2020-10-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_blog_allow_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='allow_dark_mode',
        ),
    ]
