# Generated by Django 3.1.14 on 2024-08-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_auto_20240801_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='deprioritise',
        ),
    ]
