# Generated by Django 3.2.23 on 2024-08-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_remove_blog_deprioritise'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
