# Generated by Django 3.0.7 on 2020-10-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_remove_blog_allow_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='external_stylesheet',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
