# Generated by Django 3.0.7 on 2020-10-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_blog_external_stylesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favicon',
            field=models.CharField(default='🐼', max_length=10),
        ),
    ]
