# Generated by Django 3.0.7 on 2020-10-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_blog_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='favicon',
            field=models.CharField(default='🐼', max_length=1),
        ),
    ]
