# Generated by Django 3.2.23 on 2024-08-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_auto_20240821_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='max_blogs',
            field=models.IntegerField(default=10),
        ),
    ]
