# Generated by Django 3.0.7 on 2021-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_auto_20201103_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='favicon',
            field=models.CharField(default='🐼', max_length=4),
        ),
    ]
