# Generated by Django 3.2.23 on 2024-10-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_blog_optimise_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pinned',
        ),
    ]
