# Generated by Django 3.0.7 on 2021-03-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_auto_20210205_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fathom_site_id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
