# Generated by Django 3.2.23 on 2024-10-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_remove_post_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lang',
            field=models.CharField(blank=True, db_index=True, default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='lang',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
