# Generated by Django 3.2.23 on 2024-10-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0029_auto_20241022_1206'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='upvote',
            index=models.Index(fields=['post', 'hash_id'], name='blogs_upvot_post_id_537a4b_idx'),
        ),
    ]
