# Generated by Django 3.2.23 on 2024-10-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0030_upvote_blogs_upvot_post_id_537a4b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
