# Generated by Django 3.0.7 on 2021-04-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0030_remove_blog_remove_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailer',
            fields=[
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blogs.Blog')),
                ('notify_users', models.BooleanField(default=False)),
            ],
        ),
    ]
