# Generated by Django 3.0.7 on 2021-04-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0031_emailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailer',
            old_name='notify_users',
            new_name='notify',
        ),
    ]
