# Generated by Django 3.2.23 on 2024-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0032_auto_20241022_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='browser',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='device',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='hash_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='referrer',
            field=models.URLField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
