# Generated by Django 3.0.7 on 2021-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0033_emailer_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emailer',
            name='notification_text',
            field=models.TextField(blank=True, default="Hey, I've just published a new post! Check out the link below."),
        ),
    ]
