# Generated by Django 3.0.7 on 2021-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0034_auto_20210511_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
