# Generated by Django 3.2.23 on 2024-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0034_auto_20241022_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsssubscriber',
            name='access_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rsssubscriber',
            name='hash_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
