# Generated by Django 3.2.23 on 2024-10-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0035_auto_20241029_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='dodginess_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='ignored_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_posted',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='to_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='first_published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='shadow_votes',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='upgraded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='upgraded_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
