# Generated by Django 3.0.7 on 2021-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0035_auto_20210521_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='challenge',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
