# Generated by Django 3.2.23 on 2024-11-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0036_auto_20241029_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='browser',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='device',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='hash_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='referrer',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rsssubscriber',
            name='access_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rsssubscriber',
            name='hash_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['post', 'created_date'], name='blogs_hit_post_id_bcc9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['post', 'hash_id'], name='blogs_hit_post_id_ffb8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['post', 'referrer'], name='blogs_hit_post_id_2ead4f_idx'),
        ),
        migrations.AddIndex(
            model_name='rsssubscriber',
            index=models.Index(fields=['blog', 'access_date'], name='blogs_rsssu_blog_id_062df2_idx'),
        ),
    ]
