# Generated by Django 3.0.7 on 2021-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0036_blog_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
