# Generated by Django 3.2.23 on 2024-11-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0037_auto_20241119_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='codemirror_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
