# Generated by Django 3.0.7 on 2021-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0037_blog_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lang',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
    ]
