# Generated by Django 3.0.7 on 2021-07-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0038_auto_20210629_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='nav',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
