# Generated by Django 3.2.23 on 2025-01-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0038_blog_codemirror_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='all_tags',
            field=models.TextField(default='[]'),
        ),
    ]
