# Generated by Django 5.1.6 on 2025-02-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0039_blog_all_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nAllow: /'),
        ),
    ]
