# Generated by Django 3.0.7 on 2021-07-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0039_blog_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, default='Hello World!'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='nav',
            field=models.CharField(blank=True, default='[Home](/) [Blog](/blog/)', max_length=500),
        ),
    ]
