# Generated by Django 5.1.6 on 2025-02-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0040_alter_blog_robots_txt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RssSubscriber',
        ),
    ]
