# Generated by Django 5.1.6 on 2025-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0041_delete_rsssubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
