# Generated by Django 3.0.7 on 2021-09-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0042_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='icon_url',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
