# Generated by Django 5.1.6 on 2025-03-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0042_blog_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='permanent_ignore',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
