# Generated by Django 3.0.7 on 2021-09-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0043_auto_20210918_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='optimised_url',
        ),
    ]
