# Generated by Django 5.1.6 on 2025-03-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0043_blog_permanent_ignore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
