# Generated by Django 5.1.6 on 2025-04-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0044_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='posts_in_last_24_hours',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
