# Generated by Django 3.1.14 on 2022-05-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0045_auto_20210921_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='overwrite_styles',
            field=models.BooleanField(choices=[(True, 'Overwrite stylesheet'), (False, 'Extend stylesheet')], default=False),
        ),
    ]
