# Generated by Django 5.1.6 on 2025-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0045_blog_posts_in_last_24_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='order_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
