# Generated by Django 5.1.6 on 2025-06-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0046_usersettings_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentstore',
            name='review_blacklist_terms',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
