# Generated by Django 3.1.14 on 2022-05-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0046_blog_overwrite_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='overwrite_styles',
            field=models.BooleanField(choices=[(True, 'Overwrite styles'), (False, 'Extend existing styles')], default=False, verbose_name=''),
        ),
    ]
