# Generated by Django 5.1.6 on 2025-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0047_persistentstore_review_blacklist_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentstore',
            name='reviewed_blogs',
            field=models.JSONField(default=dict),
        ),
    ]
