# Generated by Django 4.0.4 on 2022-06-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0048_remove_image_blog_delete_emailer_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='blog',
            name='upgraded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
