# Generated by Django 5.1.6 on 2025-10-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0048_persistentstore_review_reviewed_blogs_squashed_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
