# Generated by Django 4.0.4 on 2022-06-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0049_remove_blog_subscribed_blog_upgraded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='challenge',
        ),
    ]
