# Generated by Django 5.1.6 on 2025-08-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0048_persistentstore_review_reviewed_blogs_squashed_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='max_feed_entries',
            field=models.IntegerField(default=10),
        ),
    ]
