# Generated by Django 4.0.4 on 2022-06-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0050_remove_blog_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
