# Generated by Django 5.1.6 on 2025-10-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0050_usersettings_welcome_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='welcome_email_sent',
            new_name='upgraded_email_sent',
        ),
    ]
