# Generated by Django 5.1.6 on 2025-10-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0051_rename_welcome_email_sent_usersettings_upgraded_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='posts_in_last_24_hours',
            new_name='posts_in_last_12_hours',
        ),
    ]
