# Generated by Django 4.0.4 on 2022-06-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0052_post_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_tag',
            field=models.CharField(blank=True, default="<meta name='' property='' content='' />", max_length=500),
        ),
    ]
