# Generated by Django 5.2.8 on 2025-11-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0052_rename_posts_in_last_24_hours_blog_posts_in_last_12_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='browser',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
