# Generated by Django 5.2.8 on 2025-11-19 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0053_alter_hit_browser_alter_hit_country_alter_hit_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.post'),
        ),
    ]
