# Generated by Django 4.0.4 on 2022-07-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0054_blog_dark_mode_alter_blog_meta_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='show_in_feed',
            new_name='make_discoverable',
        ),
    ]
