# Generated by Django 5.2.8 on 2025-11-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0054_alter_hit_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog'),
        ),
    ]
