# Generated by Django 4.0.4 on 2022-07-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0055_rename_show_in_feed_post_make_discoverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='old_editor',
            field=models.BooleanField(default=False),
        ),
    ]
