# Generated by Django 5.2.8 on 2025-11-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0055_hit_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='analytics_update',
            field=models.BooleanField(default=False),
        ),
    ]
