# Generated by Django 5.2.8 on 2025-11-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0056_blog_analytics_update'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hit',
            name='blogs_hit_post_id_bcc9f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='hit',
            name='blogs_hit_post_id_ffb8fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='hit',
            name='blogs_hit_post_id_2ead4f_idx',
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['blog', 'post', 'created_date', 'referrer'], name='hit_blog_post_date_ref'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['blog', 'created_date', 'post', 'referrer', 'hash_id'], name='hit_visitors_opt'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['blog', 'created_date'], name='hit_blog_date'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['blog', 'created_date', 'device'], name='hit_blog_date_device'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['blog', 'created_date', 'browser'], name='hit_blog_date_browser'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['blog', 'created_date', 'country'], name='hit_blog_date_country'),
        ),
    ]
