# Generated by Django 4.0.4 on 2022-07-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0056_blog_old_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta_tag',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
