# Generated by Django 5.2.9 on 2026-01-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0057_remove_hit_blogs_hit_post_id_bcc9f1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='discovery_hide_list',
            field=models.JSONField(default=dict),
        ),
    ]
