# Generated by Django 5.2.9 on 2026-01-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0058_usersettings_discovery_hide_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='discovery_hide_list',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
