# Generated by Django 5.1.6 on 2026-01-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0058_usersettings_discovery_hide_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='show_on_discover',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
