# Generated by Django 4.0.4 on 2022-07-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0059_alter_blog_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='overwrite_styles',
            field=models.BooleanField(choices=[(True, 'Overwrite styles'), (False, 'Extend default styles')], default=False, verbose_name=''),
        ),
    ]
