# Generated by Django 5.2.11 on 2026-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0059_alter_usersettings_discovery_hide_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='orphaned_domain_warning_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
