# Generated by Django 5.2.11 on 2026-02-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0060_usersettings_orphaned_domain_warning_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('yearly', 'yearly'), ('lifetime', 'lifetime')], max_length=20, null=True),
        ),
    ]
