# Generated by Django 4.0.4 on 2022-07-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0060_alter_blog_overwrite_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stylesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('identifier', models.SlugField(max_length=100, unique=True)),
                ('css', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='overwrite_styles',
            field=models.BooleanField(choices=[(True, 'Overwrite default styles'), (False, 'Extend default styles')], default=False, verbose_name=''),
        ),
    ]
