# Generated by Django 4.0.4 on 2022-07-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0061_stylesheet_alter_blog_overwrite_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesheet',
            name='external',
            field=models.BooleanField(default=False),
        ),
    ]
