# Generated by Django 5.2.11 on 2026-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0061_add_plan_type_to_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='upgrade_nudge_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
