# Generated by Django 4.0.4 on 2022-08-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0062_stylesheet_external'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='external_stylesheet',
        ),
        migrations.AlterField(
            model_name='blog',
            name='nav',
            field=models.CharField(blank=True, default='[Home](/) [Blog](/blog/)', max_length=500),
        ),
    ]
