# Generated by Django 5.2.11 on 2026-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0062_usersettings_upgrade_nudge_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='contribution_nudge_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
