# Generated by Django 5.2.11 on 2026-03-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0063_usersettings_contribution_nudge_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='optimise_images',
        ),
    ]
