# Generated by Django 4.0.4 on 2022-07-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0063_remove_blog_external_stylesheet_alter_blog_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.JSONField(default={}),
        ),
    ]
