# Generated by Django 4.0.4 on 2022-08-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0064_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='referrer',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
