# Generated by Django 4.0.4 on 2022-07-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0064_post_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hits',
            field=models.JSONField(default=dict),
        ),
    ]
