# Generated by Django 5.2.12 on 2026-03-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0065_post_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='analytics_update',
        ),
    ]
