# Generated by Django 4.0.4 on 2022-08-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0065_hit_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hit',
            name='ip_address',
            field=models.CharField(max_length=100),
        ),
    ]
