# Generated by Django 4.0.4 on 2022-08-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0066_hit_country_alter_hit_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hit',
            name='device',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hit',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hit',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
    ]
