# Generated by Django 6.0.4 on 2026-07-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0067_post_content_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['blog', 'hash_id', 'post'], name='hit_blog_hash_post'),
        ),
    ]
