# Generated by Django 4.0.4 on 2022-08-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0067_hit_browser_hit_device_alter_hit_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='public_analytics',
            field=models.BooleanField(default=False),
        ),
    ]
