# Generated by Django 6.0.6 on 2026-07-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0068_hit_hit_blog_hash_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='search_vector',
        ),
    ]
