# Generated by Django 6.0.6 on 2026-09-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0069_remove_post_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='payment_management_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
