# Generated by Django 6.0.6 on 2026-08-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0069_remove_post_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistentstore',
            name='reviewed_blogs',
        ),
    ]
