# Generated by Django 6.0.6 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0070_remove_persistentstore_reviewed_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upvote',
            name='marked_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
