# Generated by Django 4.0.4 on 2022-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0070_blog_post_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
