# Generated by Django 4.0.4 on 2022-08-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0072_post_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
