# Generated by Django 4.0.4 on 2022-09-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0073_alter_blog_last_modified_alter_post_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alias',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
