# Generated by Django 4.0.4 on 2022-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0074_post_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_path',
            field=models.CharField(default='blog', max_length=200),
        ),
    ]
