# Generated by Django 6.0.8 on 2026-09-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0070_usersettings_payment_management_url'),
        ('blogs', '0076_remove_blog_to_review_reviewer_note'),
    ]

    operations = [
    ]
