# Generated by Django 4.0.4 on 2022-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0077_alter_post_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='analytics_active',
            field=models.BooleanField(default=True),
        ),
    ]
