# Generated by Django 6.0.8 on 2026-09-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0077_merge_20260925_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='auth_token',
        ),
    ]
