# Generated by Django 3.1.14 on 2023-03-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0078_blog_analytics_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='order_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
