# Generated by Django 6.0.8 on 2026-09-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0078_remove_blog_auth_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersistentStore',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='dodginess_score',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='ignored_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='permanent_ignore',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='reviewed',
        ),
    ]
