# Generated by Django 3.1.14 on 2023-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0079_blog_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
