# Generated by Django 6.0.8 on 2026-09-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0079_delete_persistentstore_remove_blog_dodginess_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='fathom_site_id',
        ),
    ]
