# Generated by Django 3.1.14 on 2023-04-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0081_blog_to_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reviewer_note',
            field=models.TextField(blank=True),
        ),
    ]
