# Generated by Django 3.1.14 on 2023-05-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0083_auto_20230425_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_format',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
