# Generated by Django 3.1.14 on 2023-07-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0084_blog_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesheet',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
