# Generated by Django 3.1.14 on 2023-11-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0085_stylesheet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='ip_address',
            new_name='hash_id',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='ip_address',
            new_name='hash_id',
        ),
    ]
