# Generated by Django 3.1.14 on 2023-11-02 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0086_auto_20231101_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scrubbed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
