# Generated by Django 3.1.14 on 2023-11-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0087_persistentstore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persistentstore',
            old_name='last_scrubbed',
            new_name='last_executed',
        ),
    ]
