# Generated by Django 3.1.14 on 2023-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0088_auto_20231102_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='all_tags',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
