# Generated by Django 3.1.14 on 2023-11-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0089_post_all_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='all_tags',
            field=models.TextField(default='[]'),
        ),
    ]
