# Generated by Django 3.1.14 on 2023-11-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0090_auto_20231108_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='old_editor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
