# Generated by Django 3.1.14 on 2023-11-09 07:42

from django.db import migrations, models
import random
import string

def create_uid(apps, schema_editor):
    Post = apps.get_model('blogs', 'Post')
    for post in Post.objects.all():
        allowed_chars = string.ascii_letters.replace('O', '').replace('l', '')
        post.uid = ''.join(random.choice(allowed_chars) for _ in range(20))
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0092_auto_20231108_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(create_uid)
    ]
