# Generated by Django 3.1.14 on 2023-11-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0093_post_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='browser',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='device',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='hash_id',
            field=models.CharField(max_length=200),
        ),
    ]
