# Generated by Django 3.1.14 on 2023-12-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0095_post_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='auth_token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
