# Generated by Django 3.1.14 on 2024-01-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0097_rsssubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='nav',
            field=models.CharField(blank=True, default='[Home](/) [Blog](/blog/)', max_length=1000),
        ),
    ]
