# Generated by Django 3.1.14 on 2024-02-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0098_auto_20240131_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rss_alias',
            field=models.CharField(blank=True, default='atom', max_length=100),
        ),
    ]
